In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv', low_memory=False)

In [3]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [5]:
movies = movies.merge(credits, on='title')

In [6]:
movies.shape

(4809, 23)

In [7]:
credits.shape

(4803, 4)

In [8]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [9]:
# genre
# id
# keywords
# title
# overview
# release date(add afterwards)
# cast
# crew

movies = movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]

In [10]:
print(movies.columns)

Index(['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew'], dtype='object')

In [11]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 300.6+ KB

In [12]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [13]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [14]:
movies.dropna(inplace=True)

In [15]:
movies.duplicated().sum()

0

In [16]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [17]:
import ast 
def convert(obj):
    l = []
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

In [18]:
movies['genres'] = movies['genres'].apply(convert)

In [19]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
movies['keywords'] = movies['keywords'].apply(convert)

In [21]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [22]:
import ast 
def convert3(obj):
    l = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter!=3:
            l.append(i['name'])
            counter += 1
        else:
            break
    return l

In [23]:
movies['cast'] = movies['cast'].apply(convert3)

In [24]:
def fetch_director(obj):
    l = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            l.append(i['name'])
            break
    return l

In [25]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [26]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [27]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [28]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [29]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [30]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [31]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [32]:
movies

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller]","[unitedstates–mexicobarrier, legs, arms, paper...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez],"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance]",[],"[EdwardBurns, KerryBishé, MarshaDietlein]",[EdwardBurns],"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TVMovie]","[date, loveatfirstsight, narration, investigat...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith],"[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...",[],[],"[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia],"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...",[Documentary],"[obsession, camcorder, crush, dreamgirl]","[DrewBarrymore, BrianHerzlinger, CoreyFeldman]",[BrianHerzlinger],"[Ever, since, the, second, grade, when, he, fi..."

In [33]:
new_df =movies[['movie_id', 'title', 'tags']]

In [34]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

C:\Users\Dell\AppData\Local\Temp\ipykernel_1508\1824047427.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [35]:
new_df

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...

In [36]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [37]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\Dell\AppData\Local\Temp\ipykernel_1508\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [38]:
new_df

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,a newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,when ambitious new york attorney sam is sent t...
4808,25975,My Date with Drew,ever since the second grade when he first saw ...

In [39]:
import nltk

In [40]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [41]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [42]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\Dell\AppData\Local\Temp\ipykernel_1508\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [43]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [44]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1000, stop_words='english')

In [45]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [46]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [47]:
cv.get_feature_names()

D:\Software\JupitarLab\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '10',
 '1950',
 '1970',
 '3d',
 'abandon',
 'abus',
 'accept',
 'accid',
 'accident',
 'act',
 'action',
 'actor',
 'actual',
 'adapt',
 'addict',
 'adopt',
 'adulteri',
 'adventur',
 'affair',
 'affect',
 'africa',
 'african',
 'aftercreditssting',
 'age',
 'agent',
 'ago',
 'agre',
 'aid',
 'airplan',
 'alcohol',
 'alex',
 'alien',
 'alive',
 'alli',
 'allow',
 'alway',
 'america',
 'american',
 'ancient',
 'angel',
 'angeles',
 'ani',
 'anim',
 'anoth',
 'answer',
 'anyth',
 'apart',
 'apocalypt',
 'appear',
 'arm',
 'armi',
 'arrest',
 'arriv',
 'art',
 'artist',
 'ask',
 'aspir',
 'assassin',
 'assign',
 'assist',
 'astronaut',
 'attack',
 'attempt',
 'attract',
 'author',
 'away',
 'babi',
 'bad',
 'band',
 'bank',
 'bar',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedonnovel',
 'basedontruestori',
 'basedonyoungadultnovel',
 'basketbal',
 'battl',
 'beach',
 'bear',
 'beat',
 'beauti',
 'becaus',
 'becom',
 'befor',
 'befriend',
 'begin',
 'believ',
 'belov',
 'ben',
 'benstil',
 'berlin',
 'best',
 'bestfriend',
 'betray',
 'better',
 'big',
 'biographi',
 'birthday',
 'black',
 'blackmail',
 'blood',
 'bodi',
 'bomb',
 'bond',
 'book',
 'born',
 'boss',
 'box',
 'boy',
 'boyfriend',
 'break',
 'bring',
 'british',
 'brother',
 'brotherbrotherrelationship',
 'brothersisterrelationship',
 'brucewilli',
 'brutal',
 'buddi',
 'build',
 'busi',
 'businessman',
 'california',
 'camp',
 'cancer',
 'captain',
 'captur',
 'car',
 'care',
 'career',
 'carri',
 'case',
 'cast',
 'cat',
 'catch',
 'caught',
 'caus',
 'celebr',
 'center',
 'centuri',
 'century',
 'challeng',
 'chanc',
 'chang',
 'charact',
 'charg',
 'charli',
 'chase',
 'chicago',
 'child',
 'childhood',
 'children',
 'china',
 'christian',
 'christma',
 'church',
 'cia',
 'citi',
 'city',
 'civil',
 'claim',
 'class',
 'classic',
 'clinteastwood',
 'close',
 'club',
 'coach',
 'collect',
 'colleg',
 'come',
 'comedi',
 'comic',
 'comingofag',
 'command',
 'commit',
 'commun',
 'compani',
 'compet',
 'competit',
 'complet',
 'complic',
 'comput',
 'confront',
 'connect',
 'conspiraci',
 'continu',
 'control',
 'convict',
 'convinc',
 'cop',
 'corpor',
 'corrupt',
 'countri',
 'country',
 'coupl',
 'courag',
 'cours',
 'court',
 'cover',
 'crash',
 'creat',
 'creatur',
 'crew',
 'crime',
 'crimin',
 'cross',
 'crush',
 'curs',
 'dad',
 'danc',
 'dancer',
 'danger',
 'danni',
 'dark',
 'date',
 'daughter',
 'david',
 'day',
 'dead',
 'deadli',
 'deal',
 'dealer',
 'death',
 'decid',
 'deep',
 'defeat',
 'defend',
 'demand',
 'demon',
 'desert',
 'desir',
 'desper',
 'despit',
 'destroy',
 'detect',
 'determin',
 'develop',
 'die',
 'differ',
 'dinosaur',
 'direct',
 'director',
 'disappear',
 'discov',
 'discoveri',
 'divorc',
 'doctor',
 'documentari',
 'doe',
 'doesn',
 'dog',
 'don',
 'door',
 'dr',
 'dragon',
 'drama',
 'drawn',
 'dream',
 'drink',
 'drive',
 'driver',
 'drug',
 'drugdeal',
 'dure',
 'duringcreditssting',
 'dyinganddeath',
 'dystopia',
 'earli',
 'earth',
 'east',
 'eccentr',
 'effort',
 'elit',
 'embark',
 'emot',
 'encount',
 'end',
 'enemi',
 'engag',
 'england',
 'english',
 'enlist',
 'enter',
 'entir',
 'epic',
 'escap',
 'especi',
 'estrang',
 'eve',
 'event',
 'eventu',
 'everi',
 'everyon',
 'everyth',
 'evil',
 'ex',
 'execut',
 'exist',
 'experi',
 'explor',
 'explos',
 'expos',
 'extrem',
 'eye',
 'face',
 'fail',
 'faith',
 'fall',
 'fame',
 'famili',
 'family',
 'famou',
 'fantasi',
 'far',
 'farm',
 'fast',
 'fate',
 'father',
 'fathersonrelationship',
 'fbi',
 'fear',
 'featur',
 'feel',
 'fellow',
 'femal',
 'femalenud',
 'fiction',
 'fight',
 'fighter',
 'figur',
 'film',
 'filmmak',
 'final',
 'flashback',
 'fli',
 'florida',
 'follow',
 'food',
 'forc',
 'foreign',
 'forest',
 'forever',
 'form',
 'franc',
 'frank',
 'free',
 'freedom',
 'french',
 'friend',
 'friends',
 'friendship',
 'funer',
 'futur',
 'future',
 'game',
 'gang',
 'gangster',
 'gay',
 'gener',
 'georg',
 'ghost',
 'gift',
 'girl',
 'girlfriend',
 'global',
 'god',
 'goe',
 'gold',
 'gone',
 'good',
 'gore',
 'govern',
 'graduat',
 'great',
 'greatest',
 'green',
 'group',
 'grow',
 'grown',
 'guard',
 'gun',
 'guy',
 'ha',
 'half',
 'hand',
 'happen',
 'happi',
 'hard',
 'harri',
 'haunt',
 'head',
 'heart',
 'heist',
 'helicopt',
 'hell',
 'help',
 'henri',
 'hero',
 'hi',
 'hide',
 'high',
 'highschool',
 'hip',
 'hire',
 'histori',
 'hit',
 'hitman',
 'hold',
 'holiday',
 'hollywood',
 'home',
 'hometown',
 'hop',
 'hope',
 'horror',
 'hors',
 'hospit',
 'hostag',
 'hot',
 'hotel',
 'hour',
 'hous',
 'house',
 'human',
 'hunt',
 'hunter',
 'husband',
 'ice',
 'idea',
 'ident',
 'ii',
 'ill',
 'immigr',
 'includ',
 'independentfilm',
 'india',
 'indian',
 'infidel',
 'innoc',
 'insid',
 'inspir',
 'instead',
 'intellig',
 'intern',
 'interview',
 'inventor',
 'investig',
 'invit',
 'involv',
 'irish',
 'island',
 'isn',
 'isol',
 'jack',
 'jackson',
 'jail',
 'jame',
 'japan',
 'jason',
 'jealousi',
 'jean',
 'jewish',
 'jim',
 'jimmi',
 'job',
 'joe',
 'john',
 'join',
 'journalist',
 'journey',
 'jungl',
 'just',
 'justic',
 'kevin',
 'key',
 'kid',
 'kidnap',
 'kids',
 'kill',
 'killer',
 'king',
 'kingdom',
 'knight',
 'know',
 'known',
 'la',
 'lake',
 'land',
 'late',
 'later',
 'latest',
 'law',
 'lawyer',
 'lead',
 'leader',
 'learn',
 'leav',
 'led',
 'lee',
 'left',
 'legend',
 'legendari',
 'letter',
 'lie',
 'life',
 'light',
 'like',
 'line',
 'littl',
 'live',
 'lives',
 'll',
 'lo',
 'local',
 'london',
 'londonengland',
 'lone',
 'long',
 'look',
 'lord',
 'losangel',
 'lose',
 'lost',
 'love',
 'loveofone',
 'lover',
 'luck',
 'mad',
 'mafia',
 'magic',
 'major',
 'make',
 'male',
 'man',
 'manag',
 'mani',
 'mark',
 'marri',
 'marriag',
 'martialart',
 'martin',
 'marvelcom',
 'mask',
 'master',
 'match',
 'mattdamon',
 'max',
 'mean',
 'medic',
 'meet',
 'member',
 'memori',
 'men',
 'mental',
 'mercenari',
 'mexican',
 'mexico',
 'michael',
 'middl',
 'mike',
 'militari',
 'million',
 'mind',
 'miss',
 'mission',
 'mob',
 'mobster',
 'modern',
 'mom',
 'money',
 'monster',
 'month',
 'mother',
 'mountain',
 'movi',
 'movie',
 'mr',
 'murder',
 'music',
 'musician',
 'mutant',
 'mysteri',
 'nation',
 'natur',
 'nazi',
 'near',
 'need',
 'neighbor',
 'neighborhood',
 'neo',
 'new',
 'newlov',
 'newyork',
 'newyorkc',
 'nick',
 'nicolascag',
 'night',
 'nightclub',
 'nightmar',
 'noth',
 'notori',
 'novel',
 'nuclear',
 'nuditi',
 'number',
 'obsess',
 'ocean',
 'offer',
 'offic',
 'old',
 'older',
 'onc',
 'onli',
 'open',
 'oper',
 'opportun',
 'order',
 'ordinari',
 'organ',
 'origin',
 'orphan',
 'outlaw',
 'overcom',
 'owner',
 'pair',
 'pal',
 'parent',
 'parents',
 'pari',
 'park',
 'parti',
 'partner',
 'pass',
 'passion',
 'past',
 'path',
 'paul',
 'pay',
 'peac',
 'peopl',
 'people',
 'perfect',
 'perform',
 'person',
 'peter',
 'photograph',
 'pilot',
 'pirat',
 'place',
 'plan',
 'plane',
 'planet',
 'play',
 'player',
 'plot',
 'point',
 'polic',
 'polit',
 'politician',
 'popular',
 'possess',
 'possibl',
 'post',
 'power',
 'pregnant',
 'prepar',
 'present',
 'presid',
 'prevent',
 'priest',
 'princ',
 'princess',
 'prison',
 'privat',
 'problem',
 'process',
 'produc',
 'profession',
 'professor',
 'program',
 'promis',
 'prostitut',
 'protect',
 'prove',
 'psychiatrist',
 'psychopath',
 'public',
 'pull',
 'pursu',
 'queen',
 'quest',
 'question',
 'quickli',
 'race',
 'radio',
 'rais',
 'rape',
 'ray',
 'reach',
 'readi',
 'real',
 'realiti',
 'realiz',
 'realli',
 'rebel',
 'receiv',
 'recent',
 'record',
 'recov',
 'recruit',
 'relationship',
 'releas',
 'remain',
 'remak',
 'remot',
 'report',
 'rescu',
 'research',
 'resid',
 'resist',
 'respons',
 'rest',
 'restaur',
 'result',
 'retir',
 'return',
 'reunit',
 'reveal',
 'reveng',
 'revenge',
 'rich',
 'richard',
 'ride',
 'right',
 'ring',
 'rise',
 'risk',
 'rival',
 'rivalri',
 'road',
 'rob',
 'robberi',
 'robert',
 'robertdeniro',
 'robot',
 'rock',
 'role',
 'romanc',
 'romant',
 'romanticcomedi',
 'room',
 'rule',
 'run',
 'russian',
 'ruthless',
 'ryan',
 'safe',
 'sam',
 'samuell',
 'san',
 'save',
 'savingtheworld',
 'scene',
 'scheme',
 'school',
 'sciencefict',
 'scientist',
 'scott',
 'sea',
 'search',
 'season',
 'second',
 'secret',
 'secretident',
 'secur',
 'seek',
 'seemingli',
 'seen',
 'self',
 'sell',
 'send',
 'sent',
 'separ',
 'sequel',
 'seri',
 'serial',
 'serialkil',
 'serv',
 'servic',
 'set',
 'seven',
 'sever',
 'sex',
 'sexual',
 'share',
 'shark',
 'sheriff',
 'ship',
 'shock',
 'shootout',
 'shop',
 'shot',
 'sign',
 'sinc',
 'singer',
 'singl',
 'sister',
 'sistersisterrelationship',
 'situat',
 'skill',
 'slasher',
 'slave',
 'slif',
 'small',
 'smalltown',
 'snow',
 'social',
 'societi',
 'soldier',
 'someth',
 'son',
 'soon',
 'soul',
 'south',
 'space',
 'special',
 'spend',
 'spi',
 'spirit',
 'spoof',
 'sport',
 'stage',
 'stand',
 'star',
 'start',
 'state',
 'station',
 'stay',
 'steal',
 'step',
 'steve',
 'stolen',
 'stop',
 'store',
 'stori',
 'storm',
 'story',
 'strand',
 'strang',
 'stranger',
 'street',
 'strike',
 'struggl',
 'student',
 'stumbl',
 'success',
 'suddenli',
 'suffer',
 'suicid',
 'summer',
 'superhero',
 'supernatur',
 'superpow',
 'surpris',
 'surviv',
 'survivor',
 'suspect',
 'suspens',
 'taken',
 'tale',
 'talent',
 'talk',
 'target',
 'task',
 'teach',
 'teacher',
 'team',
 'technolog',
 'teen',
 'teenag',
 'televis',
 'tell',
 'terrifi',
 'terror',
 'terrorist',
 'test',
 'texa',
 'themselv',
 'thi',
 'thief',
 'thing',
 'think',
 'thought',
 'threat',
 'threaten',
 'thriller',
 'tim',
 'time',
 'timetravel',
 'togeth',
 'told',
 'tom',
 'tortur',
 'tough',
 'tour',
 'town',
 'track',
 'tragedi',
 'train',
 'transform',
 'transport',
 'trap',
 'travel',
 'tri',
 'trial',
 'trip',
 'troubl',
 'true',
 'trust',
 'truth',
 'turn',
 'tv',
 'twin',
 'ultim',
 'uncl',
 'uncov',
 'undercov',
 'underground',
 'underworld',
 'unexpect',
 'unit',
 'univers',
 'unlik',
 'usa',
 'usapresid',
 'use',
 'vacat',
 'vampir',
 'van',
 'variou',
 'veri',
 'veteran',
 'victim',
 'video',
 'villag',
 'villain',
 'violenc',
 'violent',
 'virgin',
 'viru',
 'visit',
 'wa',
 'wait',
 'wake',
 'walk',
 'wall',
 'want',
 'war',
 'warrior',
 'watch',
 'water',
 'way',
 'wealthi',
 'weapon',
 'wed',
 'week',
 'west',
 'western',
 'white',
 'widow',
 'wife',
 'wifehusbandrelationship',
 'wild',
 'william',
 'win',
 'winter',
 'wish',
 'wit',
 'witch',
 'woman',
 'womandirector',
 'women',
 'won',
 'woodyallen',
 'work',
 'worker',
 'world',
 'worldwarii',
 'writer',
 'wrong',
 'year',
 'years',
 'york',
 'young',
 'younger',
 'youth',
 'zombi']

In [48]:
from sklearn.metrics.pairwise import cosine_similarity

In [49]:
similarity = cosine_similarity(vectors)

In [50]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:11]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [55]:
recommend("f")

The Dark Knight
The Yards
10th & Wolf
Synecdoche, New York
Rockaway
Amidst the Devil's Wings
Batman
Batman
Nightcrawler
Iron Man 2

In [52]:
print(movies['title'])

0                                         Avatar
1       Pirates of the Caribbean: At World's End
2                                        Spectre
3                          The Dark Knight Rises
4                                    John Carter
                          ...
4804                                 El Mariachi
4805                                   Newlyweds
4806                   Signed, Sealed, Delivered
4807                            Shanghai Calling
4808                           My Date with Drew
Name: title, Length: 4806, dtype: object