In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv', low_memory=False)

In [3]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
credits.head(1)

,movie_id,title,cast,crew,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 1255,Unnamed: 1256,Unnamed: 1257,Unnamed: 1258,Unnamed: 1259,Unnamed: 1260,Unnamed: 1261,Unnamed: 1262,Unnamed: 1263,Unnamed: 1264
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
movies = movies.merge(credits, on='title')

In [6]:
movies.shape

(518, 1284)

In [7]:
credits.shape

(542, 1265)

In [8]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,Unnamed: 1255,Unnamed: 1256,Unnamed: 1257,Unnamed: 1258,Unnamed: 1259,Unnamed: 1260,Unnamed: 1261,Unnamed: 1262,Unnamed: 1263,Unnamed: 1264
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# genre
# id
# keywords
# title
# overview
# release date(add afterwards)
# cast
# crew

movies = movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]

In [10]:
print(movies.columns)

Index(['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew'], dtype='object')

In [11]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 518 entries, 0 to 517
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  518 non-null    object
 1   title     518 non-null    object
 2   overview  518 non-null    object
 3   genres    518 non-null    object
 4   keywords  518 non-null    object
 5   cast      517 non-null    object
 6   crew      516 non-null    object
dtypes: object(7)
memory usage: 32.4+ KB

In [12]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [13]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        1
crew        2
dtype: int64

In [14]:
movies.dropna(inplace=True)

In [15]:
movies.duplicated().sum()

0

In [16]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [17]:
import ast 
def convert(obj):
    l = []
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

In [18]:
movies['genres'] = movies['genres'].apply(convert)

In [19]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
movies['keywords'] = movies['keywords'].apply(convert)

In [21]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [22]:
import ast 
def convert3(obj):
    l = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter!=3:
            l.append(i['name'])
            counter += 1
        else:
            break
    return l

In [23]:
movies['cast'] = movies['cast'].apply(convert3)

In [24]:
def fetch_director(obj):
    l = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            l.append(i['name'])
            break
    return l

In [26]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [27]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [30]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [31]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [34]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [35]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [36]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [37]:
movies

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...,...,...,...,...,...
512,9802,The Rock,"[A, group, of, renegade, marine, commandos, se...","[Action, Adventure, Thriller]","[sanfrancisco, fbi, gasattack, alcatraz, hosta...","[SeanConnery, NicolasCage, EdHarris]",[MichaelBay],"[A, group, of, renegade, marine, commandos, se..."
513,950,Ice Age: The Meltdown,"[Diego,, Manny, and, Sid, return, in, this, se...","[Animation, Family, Comedy, Adventure]","[mammoth, sloth, iceage, barrierice, icemeltin...","[RayRomano, JohnLeguizamo, DenisLeary]",[CarlosSaldanha],"[Diego,, Manny, and, Sid, return, in, this, se..."
514,1824,50 First Dates,"[Henry, is, a, player, skilled, at, seducing, ...","[Comedy, Romance]","[dejavu, amnesia, hawaii, ladykiller, romantic...","[AdamSandler, DrewBarrymore, RobSchneider]",[PeterSegal],"[Henry, is, a, player, skilled, at, seducing, ..."
515,2976,Hairspray,"[Pleasantly, plump, teenager,, Tracy, Turnblad...","[Family, Comedy, Music, Romance]","[races, dream, dance, television, tvshow, race...","[JohnTravolta, MichellePfeiffer, ChristopherWa...",[AdamShankman],"[Pleasantly, plump, teenager,, Tracy, Turnblad..."
516,11026,Exorcist: The Beginning,"[Having, lived, through, traumatizing, events,...","[Horror, Mystery, Thriller]","[secret, obsession, exorcism, remake, priest, ...","[StellanSkarsgÃ¥rd, IzabellaScorupco, JamesD'Arcy]",[RennyHarlin],"[Having, lived, through, traumatizing, events,..."

In [40]:
new_df =movies[['movie_id', 'title', 'tags']]

In [44]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

C:\Users\Dell\AppData\Local\Temp\ipykernel_3880\1824047427.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [45]:
new_df

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
512,9802,The Rock,A group of renegade marine commandos seizes a ...
513,950,Ice Age: The Meltdown,"Diego, Manny and Sid return in this sequel to ..."
514,1824,50 First Dates,Henry is a player skilled at seducing women. B...
515,2976,Hairspray,"Pleasantly plump teenager, Tracy Turnblad and ..."
516,11026,Exorcist: The Beginning,Having lived through traumatizing events durin...

In [46]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [49]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\Dell\AppData\Local\Temp\ipykernel_3880\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [51]:
new_df

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."
...,...,...,...
512,9802,The Rock,a group of renegade marine commandos seizes a ...
513,950,Ice Age: The Meltdown,"diego, manny and sid return in this sequel to ..."
514,1824,50 First Dates,henry is a player skilled at seducing women. b...
515,2976,Hairspray,"pleasantly plump teenager, tracy turnblad and ..."
516,11026,Exorcist: The Beginning,having lived through traumatizing events durin...

In [76]:
import nltk

In [77]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [78]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [81]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\Dell\AppData\Local\Temp\ipykernel_3880\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [82]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [83]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1000, stop_words='english')

In [84]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [85]:
vectors

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [86]:
cv.get_feature_names()

['000',
 '10',
 '3d',
 'abil',
 'abl',
 'accept',
 'accident',
 'act',
 'action',
 'activ',
 'actual',
 'adamsandl',
 'adapt',
 'adopt',
 'adventur',
 'africa',
 'aftercreditssting',
 'age',
 'agent',
 'aid',
 'airplan',
 'alecbaldwin',
 'alex',
 'alien',
 'alieninvas',
 'alli',
 'allianc',
 'alter',
 'ambush',
 'america',
 'american',
 'anakin',
 'ancient',
 'angel',
 'angelinajoli',
 'ani',
 'anim',
 'annehathaway',
 'anoth',
 'anthonyhopkin',
 'anthropomorph',
 'anti',
 'anyth',
 'apart',
 'ape',
 'apocalyps',
 'apocalypt',
 'apprentic',
 'archaeologist',
 'architect',
 'arena',
 'arm',
 'armi',
 'armsdeal',
 'army',
 'arnoldschwarzenegg',
 'arriv',
 'art',
 'arthur',
 'artificialintellig',
 'artist',
 'ask',
 'assassin',
 'assign',
 'assist',
 'asteroid',
 'astronaut',
 'attack',
 'attempt',
 'australia',
 'await',
 'away',
 'bad',
 'band',
 'bank',
 'barney',
 'base',
 'basedoncomicbook',
 'basedonnovel',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'batman',
 'battl',
 'bear',
 'beast',
 'beauti',
 'becom',
 'befor',
 'begin',
 'believ',
 'belov',
 'benstil',
 'best',
 'bestfriend',
 'betray',
 'big',
 'bilbo',
 'bird',
 'black',
 'blackmag',
 'blackmail',
 'blood',
 'blu',
 'bomb',
 'bond',
 'book',
 'born',
 'boxer',
 'boy',
 'bradpitt',
 'brave',
 'braveri',
 'break',
 'brettratn',
 'bring',
 'brink',
 'british',
 'britishsecretservic',
 'broom',
 'brother',
 'brotherbrotherrelationship',
 'brothersisterrelationship',
 'bruce',
 'brucewilli',
 'brutal',
 'bryansing',
 'build',
 'busi',
 'california',
 'camerondiaz',
 'capabl',
 'captain',
 'captur',
 'car',
 'carchas',
 'career',
 'carrac',
 'carri',
 'carrie',
 'carter',
 'case',
 'casino',
 'cast',
 'cat',
 'cataclysm',
 'catastroph',
 'cateblanchett',
 'caught',
 'caus',
 'cave',
 'center',
 'centuri',
 'challeng',
 'chanc',
 'chang',
 'chao',
 'chaos',
 'charact',
 'charl',
 'chase',
 'child',
 'children',
 'china',
 'choic',
 'chriscolumbu',
 'chrisevan',
 'chrishemsworth',
 'chrispin',
 'christianbal',
 'christma',
 'church',
 'cia',
 'citi',
 'city',
 'civil',
 'classic',
 'clock',
 'clone',
 'close',
 'clue',
 'cobra',
 'code',
 'colleg',
 'combat',
 'come',
 'comedi',
 'comic',
 'command',
 'compani',
 'compet',
 'comput',
 'conan',
 'confid',
 'confront',
 'connor',
 'conspiraci',
 'contact',
 'continu',
 'control',
 'convinc',
 'cop',
 'corpor',
 'corrupt',
 'coupl',
 'cours',
 'cover',
 'crash',
 'crazi',
 'creat',
 'creatur',
 'crew',
 'crime',
 'crimefight',
 'crimin',
 'cross',
 'curs',
 'cyborg',
 'danc',
 'danger',
 'danielcraig',
 'danielradcliff',
 'danni',
 'dark',
 'daughter',
 'david',
 'day',
 'dccomic',
 'dead',
 'deadli',
 'death',
 'decept',
 'decid',
 'deep',
 'defeat',
 'defend',
 'demon',
 'denzelwashington',
 'desert',
 'desper',
 'destini',
 'destroy',
 'destruct',
 'detect',
 'determin',
 'die',
 'differ',
 'dinosaur',
 'director',
 'disappear',
 'disast',
 'disaster',
 'discov',
 'discoveri',
 'district',
 'divorc',
 'dna',
 'doctor',
 'doesn',
 'dog',
 'domin',
 'dr',
 'dragon',
 'drama',
 'dream',
 'drug',
 'dure',
 'duringcreditssting',
 'dwarv',
 'dwaynejohnson',
 'dyinganddeath',
 'dystopia',
 'dystopicfutur',
 'earth',
 'eddiemurphi',
 'effort',
 'egypt',
 'elijahwood',
 'elv',
 'embark',
 'emerg',
 'emmawatson',
 'emot',
 'emperor',
 'encount',
 'end',
 'enemi',
 'enemy',
 'engin',
 'england',
 'enlist',
 'enter',
 'entir',
 'epic',
 'era',
 'escap',
 'espionag',
 'ethan',
 'event',
 'everi',
 'everyth',
 'evil',
 'ewanmcgregor',
 'ex',
 'exist',
 'exoticisland',
 'experi',
 'explor',
 'explos',
 'face',
 'fairytal',
 'faith',
 'fall',
 'famili',
 'family',
 'fantasi',
 'fantast',
 'fantasyworld',
 'far',
 'farm',
 'fate',
 'father',
 'fathersonrelationship',
 'fbi',
 'fbiagent',
 'fear',
 'feel',
 'feet',
 'fellow',
 'fight',
 'figur',
 'film',
 'filmmak',
 'final',
 'fish',
 'fli',
 'flint',
 'flood',
 'follow',
 'food',
 'forc',
 'forest',
 'forever',
 'form',
 'francisco',
 'freedom',
 'french',
 'friend',
 'friendship',
 'fugit',
 'futur',
 'future',
 'futurist',
 'gain',
 'galaxi',
 'game',
 'gang',
 'gangster',
 'garyoldman',
 'gener',
 'genet',
 'geniu',
 'georgeclooney',
 'gerardbutl',
 'ghost',
 'giant',
 'giantrobot',
 'gift',
 'girl',
 'girlfriend',
 'gladiat',
 'global',
 'globe',
 'god',
 'goe',
 'gold',
 'golden',
 'gone',
 'good',
 'goodvsevil',
 'goreverbinski',
 'gorilla',
 'gotham',
 'gothamc',
 'govern',
 'graduat',
 'great',
 'greatest',
 'green',
 'group',
 'grow',
 'gun',
 'gunfight',
 'guy',
 'ha',
 'hacker',
 'hade',
 'halleberri',
 'hand',
 'happen',
 'harri',
 'harrisonford',
 'hawaii',
 'head',
 'heart',
 'heaven',
 'heist',
 'helicopt',
 'hell',
 'help',
 'hero',
 'heroes',
 'heroic',
 'hi',
 'hidden',
 'hide',
 'high',
 'histori',
 'hit',
 'hobbit',
 'hold',
 'holiday',
 'home',
 'homeland',
 'hope',
 'horror',
 'hospit',
 'hostag',
 'hostil',
 'hous',
 'house',
 'huge',
 'hughjackman',
 'human',
 'humanity',
 'humankind',
 'hunger',
 'hunt',
 'hunter',
 'husband',
 'ianmckellen',
 'ice',
 'ident',
 'ii',
 'imax',
 'import',
 'imposs',
 'includ',
 'incred',
 'inhabit',
 'insid',
 'inspector',
 'inspir',
 'intellig',
 'intern',
 'invad',
 'inventor',
 'investig',
 'involv',
 'island',
 'jack',
 'jackblack',
 'jackson',
 'jame',
 'jamesmcavoy',
 'jane',
 'japan',
 'jedi',
 'jeffbridg',
 'jenniferconnelli',
 'jenniferlawr',
 'jill',
 'jim',
 'job',
 'joe',
 'john',
 'johnnydepp',
 'johntravolta',
 'join',
 'joshhutcherson',
 'journalist',
 'journey',
 'judelaw',
 'jungl',
 'just',
 'katewinslet',
 'katniss',
 'keanureev',
 'kennethbranagh',
 'key',
 'kid',
 'kidnap',
 'kidsandfamili',
 'kill',
 'killer',
 'king',
 'kingdom',
 'knight',
 'know',
 'known',
 'kristenwiig',
 'kuzco',
 'land',
 'late',
 'later',
 'latest',
 'launch',
 'lava',
 'law',
 'lead',
 'leader',
 'learn',
 'leav',
 'led',
 'lee',
 'left',
 'legendari',
 'leonardodicaprio',
 'liamhemsworth',
 'liamneeson',
 'lie',
 'life',
 'lik',
 'like',
 'line',
 'lion',
 'littl',
 'live',
 'lives',
 'lo',
 'londonengland',
 'lone',
 'long',
 'look',
 'lord',
 'losangel',
 'lose',
 'loss',
 'lossoffath',
 'lost',
 'love',
 'loveofone',
 'lover',
 'machin',
 'mad',
 'madagascar',
 'magic',
 'major',
 'make',
 'man',
 'manag',
 'manhattan',
 'mankind',
 'map',
 'mar',
 'marin',
 'marri',
 'marriag',
 'martialart',
 'martinscorses',
 'marvelcinematicunivers',
 'marvelcom',
 'mask',
 'massiv',
 'master',
 'mastermind',
 'mattdamon',
 'max',
 'maximu',
 'mcclane',
 'mean',
 'meet',
 'memori',
 'men',
 'mercenari',
 'miami',
 'michaelbay',
 'middl',
 'middle',
 'mike',
 'militari',
 'million',
 'mind',
 'miss',
 'mission',
 'modern',
 'money',
 'monkey',
 'monster',
 'moon',
 'moscow',
 'mother',
 'mountain',
 'mous',
 'movi',
 'murder',
 'museum',
 'music',
 'mutant',
 'mysteri',
 'mythic',
 'mytholog',
 'narnia',
 'nasa',
 'natalieportman',
 'nation',
 'natur',
 'naturaldisast',
 'navi',
 'nazi',
 'need',
 'neighbor',
 'neo',
 'new',
 'newyork',
 'newyorkc',
 'nicolascag',
 'nicolekidman',
 'night',
 'north',
 'noth',
 'novel',
 'nuclear',
 'nurs',
 'obsess',
 'ocean',
 'offic',
 'old',
 'onc',
 'onli',
 'ontherun',
 'open',
 'oper',
 'oppos',
 'orc',
 'order',
 'ordinari',
 'organ',
 'origin',
 'orlandobloom',
 'orphan',
 'outcast',
 'outerspac',
 'outlaw',
 'owenwilson',
 'owner',
 'pack',
 'pair',
 'parent',
 'pari',
 'park',
 'parker',
 'parti',
 'partner',
 'pass',
 'past',
 'path',
 'paulwalk',
 'peac',
 'penguin',
 'peopl',
 'people',
 'perfect',
 'peril',
 'perseu',
 'person',
 'pet',
 'peter',
 'peterjackson',
 'piercebrosnan',
 'pig',
 'pilot',
 'pirat',
 'place',
 'plagu',
 'plan',
 'plane',
 'planet',
 'play',
 'plot',
 'plung',
 'po',
 'poison',
 'polic',
 'polit',
 'post',
 'power',
 'prepar',
 'presid',
 'prevent',
 'prime',
 'princ',
 'prince',
 'princess',
 'prison',
 'problem',
 'produc',
 'professor',
 'program',
 'promis',
 'protect',
 'prove',
 'public',
 'pull',
 'queen',
 'quest',
 'question',
 'race',
 'rachelweisz',
 'rais',
 'ralph',
 'rat',
 'reach',
 'real',
 'realiz',
 'rebel',
 'recov',
 'recruit',
 'releas',
 'reluctantli',
 'remain',
 'remak',
 'report',
 'rescu',
 'resist',
 'resourc',
 'respons',
 'rest',
 'restor',
 'retir',
 'return',
 'reunit',
 'reveal',
 'reveng',
 'revolut',
 'riddl',
 'ridleyscott',
 'right',
 'ring',
 'rise',
 'risk',
 'rival',
 'rivalri',
 'robert',
 'robertdowneyjr',
 'robertzemecki',
 'robinwilliam',
 'robot',
 'rogu',
 'rolandemmerich',
 'roman',
 'romanc',
 'ronhoward',
 'rosariodawson',
 'ruin',
 'rule',
 'run',
 'rupertgrint',
 'russellcrow',
 'russian',
 'ruthless',
 'ryanreynold',
 'sabotag',
 'sam',
 'samurai',
 'san',
 'sanfrancisco',
 'save',
 'savingtheworld',
 'sbook',
 'scheme',
 'school',
 'schoolofwitchcraft',
 'scienc',
 'sciencefict',
 'scientist',
 'scott',
 'sea',
 'search',
 'secret',
 'secretag',
 'secretident',
 'secur',
 'seek',
 'seemingli',
 'seen',
 'seiz',
 'self',
 'sell',
 'senat',
 'send',
 'sent',
 'sequel',
 'seri',
 'series',
 'set',
 'sever',
 'sewer',
 'shape',
 'shaw',
 'shawnlevi',
 'shialabeouf',
 'ship',
 'shipwreck',
 'shootout',
 'sid',
 'silver',
 'simon',
 'sinist',
 'sister',
 'skill',
 'slave',
 'sleep',
 'slif',
 'small',
 'smith',
 'smurf',
 'snow',
 'societi',
 'soldier',
 'someth',
 'son',
 'soon',
 'sorcerer',
 'soul',
 'south',
 'space',
 'spacecraft',
 'spacemarin',
 'spaceopera',
 'spaceship',
 'spacetravel',
 'special',
 'spi',
 'spider',
 'spirit',
 'sport',
 'stake',
 'stand',
 'star',
 'stark',
 'start',
 'state',
 'station',
 'steal',
 'stevemartin',
 'stevenspielberg',
 'stop',
 'stori',
 'storm',
 'strand',
 'strang',
 'street',
 'strength',
 'struggl',
 'student',
 'stumbl',
 'success',
 'suddenli',
 'suffer',
 'suicid',
 'super',
 'superhero',
 'superheroteam',
 'superhuman',
 'superpow',
 'supervillain',
 'surviv',
 'survivor',
 'suspect',
 'suspens',
 'sword',
 'swordandsorceri',
 'sylvesterstallon',
 'symbol',
 'taken',
 'tale',
 'talk',
 'talkinganim',
 'target',
 'task',
 'team',
 'tech',
 'technolog',
 'teenag',
 'teleport',
 'televis',
 'tell',
 'terrifi',
 'terror',
 'terrorist',
 'test',
 'themselv',
 'thi',
 'thief',
 'thing',
 'think',
 'thor',
 'thought',
 'threat',
 'threaten',
 'thriller',
 'thrown',
 'ticket',
 'tiger',
 'timburton',
 'time',
 'timetravel',
 'togeth',
 'tolkien',
 'tom',
 'tomcruis',
 'tomhank',
 'tommyleejon',
 'toretto',
 'torn',
 'tour',
 'tower',
 'town',
 'toy',
 'track',
 'trade',
 'train',
 'traitor',
 'transform',
 'transport',
 'trap',
 'travel',
 'treasur',
 'treasurehunt',
 'tri',
 'trip',
 'true',
 'truth',
 'tunnel',
 'turn',
 'turtl',
 'ultim',
 'uncl',
 'uncov',
 'undercov',
 'underworld',
 'unexpect',
 'unit',
 'univers',
 'universe',
 'unleash',
 'unlik',
 'unstopp',
 'usa',
 'use',
 'vampir',
 'vengeanc',
 'veri',
 'veteran',
 'video',
 'vigilant',
 'vike',
 'villag',
 'villain',
 'vindiesel',
 'violenc',
 'vision',
 'visit',
 'volcano',
 'wa',
 'walk',
 'wall',
 'want',
 'war',
 'warrior',
 'washingtond',
 'way',
 'weapon',
 'wed',
 'western',
 'whale',
 'white',
 'wife',
 'wild',
 'willsmith',
 'win',
 'winter',
 'wise',
 'wit',
 'witch',
 'wizard',
 'woman',
 'womandirector',
 'women',
 'wonder',
 'work',
 'world',
 'worlds',
 'worldwarii',
 'wretch',
 'year',
 'years',
 'york',
 'young',
 'zoo']

In [88]:
from sklearn.metrics.pairwise import cosine_similarity